### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by feakuru** [sabueso/ticketator#24]
requirements seem to cover far more than is needed. python-apt, e.g., cannot be installed in Ubuntu 16.04 Gnome; nevertheless the app works perfectly without it.

**Comment by sabueso** [comment]
Yes, maybe: I'm thinking and its probably be generated under a non-clear scenario. I will try to generate-it again, with only the needed requeriments. Thanks.

**Comment by feakuru** [comment]
ok, comment here when you do, I'll close the issue

**Comment by sabueso** [comment]
Done here => https://github.com/sabueso/ticketator/pull/29
