### ISSUE TITLE
static/vendors/gauge.js/

### ISSUE THREAD

**Issue by feakuru** [sabueso/ticketator#25]
the folder does not contain the /img/ folder for bootstrap 2, although it is clearly referenced by the inner asset bootstrap. it wouldn't have been an issue if collectstatic (at least when I run it on heroku) didn't fail because of it. adding the folder solves the problem.

**Comment by sabueso** [comment]
@feakuru thanks for this point. Feel free to make fork, add folder and make the PR. All help is welcomed ;)

**Comment by sabueso** [comment]
Solved here  => https://github.com/sabueso/ticketator/pull/29
