### ISSUE TITLE
Track tasks time.

### ISSUE THREAD

**Issue by alvaro-gh** [sabueso/ticketator#55]
At first it would be nice to always show microtask update time below microtask name label. I've seen that it is showed right after microtask creation but dissapears later.
Also, ticket closing timestamp can be added at ticket listing. 
Tracking how much time each task takes would be an improvement.

**Comment by sabueso** [comment]
Hi!
About creation/update time on microtask: it's a bug and must be fixed ASAP.  I've seen this some weeks ago, but we're making some improvments (like CI and others) and we don't have time to fix it , but will be as I say, ASAP.

On timestamp when closing a ticket: IMHO it's a good idea, i did not think about this, but will be treated as an improvement. 

I leave this ticket opened until we microtask issue is closed. Once did it, we shall be open for new ticket for the improvement.

**Comment by watollop** [comment]
Fixed #53 20c68e2
