### ISSUE TITLE
Installation problems on Windows 10

### ISSUE THREAD

**Issue by sherak** [sabueso/ticketator#56]
1. carriage return in .sh files -> change to line feed (Unix) 
**solution**: add file .gitattributes in root repository with the following text:
* text=auto
*.sh -text
*.yml -text
2. building database (container ticketator_db_1) - operation "gosu" not permitted 
one **solution**: make the required changes locally
3. calling python files with ./name_of_file.py
**solution**: python name_of_file.py

**Comment by sabueso** [comment]
Hi @sherak!

Maybe, we can set recomendations for Windows 10 in the README file. 
Feel free to clone, create a new branch, modify the documentation, push and make a PR about this.

I'll be gratefull if you do it! ;)

Cheers
